machine:
  services:
    - docker
dependencies:
  override:
    - docker build -t redis .
test:
  override:
    - docker run -d -p 6380:6379 -e REDIS_PASS="mypass" redis; sleep 30
    - redis-cli -a mypass -p 6380 ping | grep PONG
